import { neon } from '@neondatabase/serverless';
import { createHash, timingSafeEqual } from 'node:crypto';
const CHAPTER='1-definitions',TA_HASH='8cb174721dd8f8b3457d3845169fa426204e9489ad95c1ca9c922adf7ddd1b93';
const url=()=>process.env.QUIZ_DATABASE_URL||process.env.QUIZ_POSTGRES_URL||process.env.QUIZ_POSTGRES_PRISMA_URL||process.env.DATABASE_URL||process.env.POSTGRES_URL;
const digest=v=>createHash('sha256').update(String(v||'')).digest('hex');
const teacher=req=>{const a=Buffer.from(digest(req.headers['x-ta-passcode'])),b=Buffer.from(TA_HASH);return a.length===b.length&&timingSafeEqual(a,b)};
async function prepare(sql){await sql`CREATE TABLE IF NOT EXISTS definition_students(student_id TEXT PRIMARY KEY,student_name TEXT NOT NULL,password_salt TEXT NOT NULL,password_hash TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;await sql`CREATE TABLE IF NOT EXISTS definition_sessions(token_hash TEXT PRIMARY KEY,student_id TEXT NOT NULL REFERENCES definition_students(student_id) ON DELETE CASCADE,expires_at TIMESTAMPTZ NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`;await sql`CREATE TABLE IF NOT EXISTS definition_account_progress(student_id TEXT NOT NULL REFERENCES definition_students(student_id) ON DELETE CASCADE,chapter TEXT NOT NULL,viewed_indices JSONB NOT NULL DEFAULT '[]'::jsonb,viewed_count INTEGER NOT NULL DEFAULT 0,total_count INTEGER NOT NULL DEFAULT 0,completed BOOLEAN NOT NULL DEFAULT FALSE,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),PRIMARY KEY(student_id,chapter))`}
async function current(sql,req){const a=String(req.headers.authorization||'');if(!a.startsWith('Bearer '))return null;return (await sql`SELECT s.student_id,a.student_name FROM definition_sessions s JOIN definition_students a ON a.student_id=s.student_id WHERE s.token_hash=${digest(a.slice(7))} AND s.expires_at>NOW()`)[0]||null}
export default async function handler(req,res){if(!url())return res.status(503).json({error:'Database is not configured.'});try{const sql=neon(url());await prepare(sql);if(req.method==='GET'&&teacher(req)){const rows=await sql`SELECT a.student_id,a.student_name,COALESCE(p.viewed_count,0) viewed_count,COALESCE(p.total_count,87) total_count,COALESCE(p.completed,FALSE) completed,p.updated_at FROM definition_students a LEFT JOIN definition_account_progress p ON p.student_id=a.student_id AND p.chapter=${CHAPTER} ORDER BY p.updated_at DESC NULLS LAST,a.student_name`;return res.status(200).json(rows.map(r=>({student:r.student_name,studentId:r.student_id,viewed:r.viewed_count,total:r.total_count,completed:r.completed,updatedAt:r.updated_at?new Date(r.updated_at).toLocaleString('en-MY',{timeZone:'Asia/Kuala_Lumpur'}):'Not started'})))}const student=await current(sql,req);if(!student)return res.status(401).json({error:'Please sign in.'});if(req.method==='GET'){const rows=await sql`SELECT viewed_indices FROM definition_account_progress WHERE student_id=${student.student_id} AND chapter=${CHAPTER}`;return res.status(200).json({student:{studentId:student.student_id,name:student.student_name},seen:rows[0]?.viewed_indices||[]})}if(req.method==='POST'){const b=typeof req.body==='string'?JSON.parse(req.body):req.body,seen=[...new Set((Array.isArray(b?.seen)?b.seen:[]).map(Number).filter(n=>Number.isInteger(n)&&n>=0&&n<500))],total=Math.max(0,Math.min(500,Number(b?.total)||0)),data=JSON.stringify(seen);await sql`INSERT INTO definition_account_progress(student_id,chapter,viewed_indices,viewed_count,total_count,completed,updated_at) VALUES(${student.student_id},${CHAPTER},${data}::jsonb,${seen.length},${total},${seen.length===total&&total>0},NOW()) ON CONFLICT(student_id,chapter) DO UPDATE SET viewed_indices=${data}::jsonb,viewed_count=${seen.length},total_count=${total},completed=${seen.length===total&&total>0},updated_at=NOW()`;return res.status(200).json({ok:true})}return res.status(405).json({error:'Method not allowed.'})}catch(e){console.error(e);return res.status(500).json({error:'Unable to access progress.'})}}
